name: Build

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup MSBuild
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: Setup Nuget
      uses: warrenbuckley/Setup-Nuget@v1
     
    - name: Choco install
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install xunit -y

    - name: Nuget Restore
      run: nuget restore PicasaDatabaseReader.sln

    - name: MSBuild
      run: msbuild PicasaDatabaseReader.sln

    - name: XUnit
      run: xunit.console.exe PicasaDatabaseReader.Core.Tests\bin\Debug\netcoreapp2.1\PicasaDatabaseReader.Core.Tests.dll -xml PicasaDatabaseReader.Core.Tests.xml
      
    - uses: Update test result
      with:
        name: PicasaDatabaseReader.Core.Tests.xml
        path: PicasaDatabaseReader.Core.Tests.xml
