name: Build

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.103' # SDK Version to use.

    - name: DotNet build
      run: dotnet build -c Release

    - name: DotNet Test
      run: dotnet test -c Release --no-build

    - name: Upload Artifacts
      uses: actions/upload-artifact@master
      with:
        name: Release build
        path: PicasaDatabaseReader.Core\bin\Release\netstandard2.1\*
